# Generated by Django 5.1.4 on 2024-12-06 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('slug', models.SlugField()),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=64)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
